version: 0.2

env:
  variables:
    S3_TEMPLATE_BUCKET: "cf-templates-1j6auxe2hqnis-eu-west-1"
    STACK_NAME: "ECS-Cluster-Simple-App"
    TEMPLATE_FILE: "ECS/master.yml"
    CONFIG_FILE: "ECS/configuration.json"

phases:
  install:
    commands:
      - echo Install dependencies... `date`
      - export _VERSION=`date +%Y%m%d%H%M%S`
      - npm install jsonlint -g
  pre_build:
    commands:
      - echo Validating CFN template file... `date`
      - aws cloudformation validate-template --template-body file://$TEMPLATE_FILE
      - echo Validatig CFN parameters configfile... `date`
      - jsonlint -q $CONFIG_FILE
  build:
   commands:
      - echo Package CFN template file... `date`
      #- aws cloudformation package --template-file $TEMPLATE_FILE --s3-bucket $S3_TEMPLATE_BUCKET --s3-prefix $STACK_NAME-$_VERSION --output-template-file template.yml

artifacts:
  files:
    - template.yml
    - ECS/configuration.json
  discard-paths: yes
