version: 0.2

env:
  variables:
    S3_TEMPLATE_BUCKET: cf-templates-1j6auxe2hqnis-eu-west-1
    STACK-NAME: ECS-Cluster-Simple-App
    TEMPLATE-FILE: ECS/master.yml
    CONFIG-FILE: ECS/configuration.json

phases:
  install:
    commands:
      - echo Install dependencies...
      - npm install jsonlint -g
  pre_build:
    commands:
      - echo Validating CFN template file...
      - aws cloudformation validate-template --template-body file://$TEMPLATE-FILE
      - echo Validatig CFN parameters configfile...
      - jsonlint -q $CONFIG-FILE
  build:
    commands:
      - echo Package CFN template file...
      - aws cloudformation package \
          --template-file $TEMPLATE-FILE \
          --s3-bucket $S3_TEMPLATE_BUCKET \
          --output-template-file template.yml

artifacts:
  files:
    - template.yml
