version: 0.2

env:
  variables:
    S3_TEMPLATE_BUCKET: "cf-templates-1j6auxe2hqnis-eu-west-1"
    STACK_NAME: "ECS-Cluster-Simple-App"
    TEMPLATE_FILE: "ECS/master.yml"
    CONFIG_FILE: "ECS/configuration.json"

phases:
  install:
    commands:
      - echo "Install dependencies..."
      - npm install jsonlint -g
  pre_build:
    commands:
      - echo "Validating CFN template file..."
      - aws cloudformation validate-template --template-body file://$TEMPLATE_FILE
      - echo "Validatig CFN parameters configfile..."
      - jsonlint -q $CONFIG_FILE
  build:
    commands:
      - echo "Package CFN template file..."
      - aws cloudformation package \
          --template-file $TEMPLATE_FILE \
          --s3-bucket $S3_TEMPLATE_BUCKET \
          --output-template-file template.yml

artifacts:
  files:
    - template.yml
