AWSTemplateFormatVersion: "2010-09-09"
Description: Master template

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Default"
        Parameters:
          - EnvironmentName
          - TagPrefix
      - Label:
          default: "VPC"
        Parameters:
          - VpcCIDR
          - VpcPublicSubnet1
          - VpcPublicSubnet2
      - Label:
          default: "ECR"
        Parameters:
          - EcrUri
      - Label:
          default: "ECS"
        Parameters:
          - EcsImage
          - EcsCMD
          - EcsDefaultTaskDesiredContainerCount
          - EcsDefaultTaskMinContainerCount
          - EcsDefaultTaskMaxContainerCount
          - EcsAutScalingTargetValue
    ParameterLabels:
      EnvironmentName:
        default: "Environment"
      TagPrefix:
        default: "Tag Prefix"
      VpcCIDR:
        default: "1. VPC CDIR"
      VpcPublicSubnet1:
        default: "2. Public Subnet 1 - AZ1"
      VpcPublicSubnet2:
        default: "3. Public Subnet 2 - AZ2"
      EcrUri:
        default: "1. ECR Repository Uri"
      EcsImage:
        default: "1. Image for the container"
      EcsCMD:
        default: "2. ECS CMD"
      EcsDefaultTaskDesiredContainerCount:
        default: "3. Desired Task Count"
      EcsDefaultTaskMinContainerCount:
        default: "4. Min Task Count"
      EcsDefaultTaskMaxContainerCount:
        default: "5. Max Task Count"
      EcsAutScalingTargetValue:
        default: "6. Scaling Target Value"

Parameters:
  #default
  EnvironmentName:
    Type: String
    Description: Environment name - dev or prod
#    Default: dev
    AllowedValues: [dev, prod]
    ConstraintDescription: Specify either dev or prod
  TagPrefix:
    Type: String
    Description: Enter Prefix that should be used for Tags.
#    Default: MyApp
  # VPC
  VpcCIDR:
    Type: String
    Description: CIDR block should be used to create the VPC (e.g. 172.21.1.0/24)
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{2})"
    ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/x. (e.g. 172.21.1.0/24)
#    Default: 172.21.1.0/24
  VpcPublicSubnet1:
    Type: String
    Description: CIDR block should be used to create the public subnet in AZ1 (e.g. 172.21.1.0/26)
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{2})"
    ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/x. (e.g. 172.21.1.0/26)
#    Default: 172.21.1.0/26
  VpcPublicSubnet2:
    Type: String
    Description: CIDR block should be used to create the public subnet in AZ1 (e.g. 172.21.1.64/26)
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{2})"
    ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/x. (e.g. 172.21.1.64/26)
#    Default: 172.21.1.64/26
  #ECR
  EcrUri:
    Type: String
    Description: Uri of the ECR Repository (e. g. ACCOUNTID.dkr.ecr.REGION.amazonaws.com/REPOSITORY)
  #ECS
  EcsImage:
    Type: String
    Description: The image to use for a container (e. g. image:tag)
#    Default: my_app_repo:latest
  EcsCMD:
    Type: String
    Description: The CMD value to pass to the container
  EcsDefaultTaskDesiredContainerCount:
    Type: Number
    Description: The desired count of Tasks
    MinValue: 0
    MaxValue: 100
#    Default: 0
  EcsDefaultTaskMinContainerCount:
    Type: Number
    Description: The min count of Tasks
    MinValue: 0
    MaxValue: 100
#    Default: 0
  EcsDefaultTaskMaxContainerCount:
    Type: Number
    Description: The max count of Tasks
    MinValue: 0
    MaxValue: 100
#    Default: 5
  EcsAutScalingTargetValue:
    Type: Number
    Description: The target value for the AutoScaling Metric ALBRequestCountPerTarget
    MinValue: 1
    MaxValue: 100
#    Default: 5

Resources:
  VPC:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: infrastructure/vpc.yml
      Parameters:
        VPCCIDR: !Ref VpcCIDR
        PublicSubnet1: !Ref VpcPublicSubnet1
        PublicSubnet2: !Ref VpcPublicSubnet2
        EnvironmentName: !Ref EnvironmentName
        TagPrefix: !Ref TagPrefix
  EC2:
    Type: 'AWS::CloudFormation::Stack'
    DependsOn: [VPC]
    Properties:
      TemplateURL: infrastructure/ec2.yml
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        TagPrefix: !Ref TagPrefix
        VPCId: !GetAtt VPC.Outputs.VPCID
        PublicSubnet1: !GetAtt VPC.Outputs.PublicSubnet1
        PublicSubnet2: !GetAtt VPC.Outputs.PublicSubnet2
        SecurityGroup: !GetAtt VPC.Outputs.SecurityGroupId
  ECS:
    Type: 'AWS::CloudFormation::Stack'
    DependsOn: [EC2]
    Properties:
      TemplateURL: infrastructure/ecs.yml
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        TagPrefix: !Ref TagPrefix
        EcrUri: !Ref EcrUri
        Image: !Ref EcsImage
        CMD: !Ref EcsCMD
        LoadBalancerName: !GetAtt EC2.Outputs.LoadBalancerName
        LoadBalancerId: !Select [2, !Split ["/", !GetAtt EC2.Outputs.LoadBalancerArn]]
        TargetGroupName: !GetAtt EC2.Outputs.TargetGroupName
        TargetGroupId: !Select [2, !Split ["/", !GetAtt EC2.Outputs.TargetGroupArn]]
        TargetGroupArn: !GetAtt EC2.Outputs.TargetGroupArn
        DefaultTaskDesiredContainerCount: !Ref EcsDefaultTaskDesiredContainerCount
        DefaultTaskMinContainerCount: !Ref EcsDefaultTaskMinContainerCount
        DefaultTaskMaxContainerCount: !Ref EcsDefaultTaskMaxContainerCount
        AutScalingTargetValue: !Ref EcsAutScalingTargetValue

Outputs:
  LoadBalancerDNSName:
    Description: "DNS name of the Load Balancer"
    Value: !GetAtt EC2.Outputs.LoadBalancerDNSName
